Feat validation
Geode-solutions/Website-Front pull request #124
Opened 2023-10-26 08:02 UTC by SpliiT

2023-10-26 09:20 UTC, JulienChampagnol requested changes

2023-10-26 09:20 UTC, JulienChampagnol commented on components/CrsSelector.json
I think you can delete this component since it's in the OGW-front library?

2023-10-26 09:20 UTC, JulienChampagnol commented on components/Tools/FileConverter/ConversionButton.vue
>                toggle_loading()
Same here

2023-10-26 09:20 UTC, JulienChampagnol commented on components/Tools/FileConverter/ExtensionSelector.json
> +    "geode_object": {}
What's the type of this param?

2023-10-26 09:20 UTC, JulienChampagnol commented on components/Tools/ValidityChecker/ResultsPanels.vue
> +    input_file_name: { type: Array, required: true },
How did it become an array ?

2023-10-26 09:20 UTC, JulienChampagnol commented on components/Tools/ValidityChecker/ResultsPanels.vue
> +    const params = {
If the variables name are matching, I don't think you have to do the name mapping

2023-10-26 09:20 UTC, JulienChampagnol commented on components/Tools/ValidityChecker/ResultsPanels.vue
> -          update_result(stepper_tree.model_checks, children_array, "error")
Why are you removing this?

2023-10-26 09:20 UTC, JulienChampagnol commented on components/constraint.json
> +  "$id": "/workflows/constraint",
I don't this this path exists

2023-10-26 09:20 UTC, JulienChampagnol commented on components/firststep.json
> +  "$id": "/workflows/implicit",
Again

2023-10-26 09:20 UTC, JulienChampagnol commented on package.json
Same as OGW-front, check for updates

2023-10-26 09:20 UTC, JulienChampagnol commented on pages/tools/crs_converter.vue
> +            schema: FileSelectorSchema,
Are you sure about the schema?

2023-10-26 09:20 UTC, JulienChampagnol commented on pages/tools/crs_converter.vue
> +            schema: FileSelectorSchema,
Same here

2023-10-26 09:20 UTC, JulienChampagnol commented on pages/tools/crs_converter.vue
> +            schema: FileSelectorSchema,
Here again

2023-10-26 09:20 UTC, JulienChampagnol commented on pages/workflows/simplex.vue
> +    return api_fetch(
api_fetch inside of api_fetch?

2023-10-26 09:20 UTC, JulienChampagnol commented on pages/workflows/simplex.vue
> +  async function next() {
Why async?

2023-10-26 09:20 UTC, JulienChampagnol commented on pages/workflows/test.json
test.json?

2023-11-02 12:47 UTC, BotellaA approved these changes

2023-11-02 12:47 UTC, BotellaA commented on components/Tools/FileConverter/ConversionButton.vue
>                fileDownload(response._data, new_file_name)
remove toogle_loading next line and check for every toogle_loading

2023-11-08 09:19 UTC, merged