first commit: Tom carousel
Geode-solutions/Website-Front pull request #138
Opened 2023-12-19 13:09 UTC by yomoxw

2023-12-19 13:25 UTC, JulienChampagnol requested changes

2023-12-19 13:25 UTC, JulienChampagnol commented on assets/img/logos/lampadaire.png
J'aurai mis le texte en bas de chaque image, là ça la coupe en deux

2023-12-19 13:25 UTC, JulienChampagnol commented on components/Common/Carousel.vue
Peut-être le bouger dans OpenGeodeWeb-Front ?

2023-12-19 13:25 UTC, JulienChampagnol commented on package-lock.json
Penser à le resupprimer, y a toujours le bug du déploiement

2023-12-19 13:28 UTC, MelchiorSchuh commented on assets/img/logos/collegue.png
Attention à l'IA avec les logos et les mains, ils sont souvent déformés bizarrement (ici le logo avec les fleches).

2023-12-19 13:28 UTC, MelchiorSchuh commented on assets/img/logos/etincelle.png
Demande peut-être à l'IA d'enlever la voiture, ca fait pas trop sobriété énergétique.

2023-12-19 13:28 UTC, MelchiorSchuh commented on assets/img/logos/geste.png
a light source -> a source

2023-12-19 13:28 UTC, MelchiorSchuh commented on assets/img/logos/lampadaire.png
illuminate -> light

2023-12-19 13:28 UTC, MelchiorSchuh commented on assets/img/logos/main.png
demande peut-être à l'IA de virer l'ampoule ici, ca fait bizarre.

2023-12-19 13:28 UTC, MelchiorSchuh commented on assets/img/logos/sobene.png
Un soleil plutot qu'une éolienne dans l'ampoule pour accentuer la lumière naturelle vs artificielle et produite pas électricité

2023-12-19 13:28 UTC, MelchiorSchuh commented on assets/img/logos/socle.png
L'écriture en dessous de la bulle est peu lisible (celle qui dit "energy sobriety")

2023-12-19 13:28 UTC, MelchiorSchuh commented on assets/img/logos/ying yang.png
J'aime bien celle-là

2023-12-20 08:29 UTC, panquez commented on assets/img/logos/derniere.png
il y a 6 doigts

2023-12-20 08:30 UTC, panquez commented on assets/img/logos/main.png
et ici seulement 4 doigts

2023-12-20 08:39 UTC, BotellaA commented on pages/software.vue
> +  import Carousel from "@geode/opengeodeweb-front/components/Carousel.vue"
on a besoin de faire ces imports explicit ?

2023-12-21 12:48 UTC, SpliiT commented on assets/img/logos/collegue.png
le texte est trop haut, je pense que ça rendrait mieux en bas de l'image

2023-12-21 12:50 UTC, SpliiT commented on assets/img/logos/dern.png
peut être descendre également le texte, l'image est sympa, peut être un peu trop futuriste mais j'aime bien

2023-12-21 12:50 UTC, SpliiT commented on assets/img/logos/derniere.png
decendre un peu le texte et changer sa couleur pour facilité la lecture

2024-01-03 13:30 UTC, closed without merging